from flask import Flask, request, render_template

app = Flask(__name__)

@app.route('/', methods=["GET", "POST"])
def gfg():
    if request.method == "POST":
        # -*- coding: utf-8 -*-
        """SimpleLinear.ipynb

        Automatically generated by Colaboratory.

        Original file is located at
            https://colab.research.google.com/drive/1CyGRSyb46O8fQ8N5fnoI90Y9V_RaX2uP#scrollTo=CFpTLdOgBb27
        """

        import numpy as np
        import pandas as pd
        import matplotlib.pyplot as plt
        
        dataset = pd.read_excel('Power Plant.xlsx')
        

        x=dataset.drop('PE',axis=1)
        y=dataset['PE'].values

        from sklearn.model_selection import train_test_split
        x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

        from sklearn.linear_model import LinearRegression
        ml=LinearRegression()
        ml.fit(x_train,y_train)

        y_pred = ml.predict(x_test) 

        p = request.form.get("input")

        Xnew = [[p]]

        result = ml.predict(Xnew)

        value = result.tolist()


        # getting input

        final=str(value[0])




        return final

    return render_template("form.html")

if __name__=='__main__':
   app.run()
